
> morningai-web@0.1.0 dev
> vite

Port 5173 is in use, trying another one...

  VITE v7.1.5  ready in 195 ms

  ➜  Local:   http://localhost:5174/
  ➜  Network: use --host to 
  #  Node.js[79504]: void node::ResetStdio
  #  Node.js[79962]: void node::ResetStdio() at ../src/node.cc:760
  #  Assertion failed: !(err != 0) || (err == -1 && (*__errno_location ()) == 1)

----- Native stack trace -----

 1: 0xf95cf7 node::Assert(node::AssertionInfo const&) [node]
 2: 0xf42264  [node]
 3: 0x7f3d09e45495  [/lib/x86_64-linux-gnu/libc.so.6]
 4: 0x7f3d09e45610 on_exit [/lib/x86_64-linux-gnu/libc.so.6]
 5: 0xe98a4f node::DefaultProcessExitHandlerInternal(node::Environment*, node::ExitCode) [node]
 6: 0xf01e4f node::Environment::Exit(node::ExitCode) [node]
 7: 0x1d755e2  [node]

  #  Node.js[79962]: void node::ResetStdio() at ../src/node.cc:760
  #  Assertion failed: !(err != 0) || (err == -1 && (*__errno_location ()) == 1)

----- Native stack trace -----

 1: 0xf95cf7 node::Assert(node::AssertionInfo const&) [node]
 2: 0xf42264  [node]
 3: 0xf42982 node::TrapWebAssemblyOrContinue(int, siginfo_t*, void*) [node]
 4: 0x7f3d09e42520  [/lib/x86_64-linux-gnu/libc.so.6]
 5: 0x1929147 v8::internal::tracing::TraceEventHelper::GetTracingController() [node]
 6: 0x13dc745 v8::internal::Isolate::CaptureDetailedStackTrace(int, v8::StackTrace::StackTraceOptions) [node]
 7: 0x126a133 v8::StackTrace::CurrentStackTrace(v8::Isolate*, int, v8::StackTrace::StackTraceOptions) [node]
 8: 0xf95c46 node::GetCurrentStackTrace(v8::Isolate*, int) [node]
 9: 0xee0c8b node::DumpJavaScriptBacktrace(_IO_FILE*) [node]
10: 0xf95d03 node::Assert(node::AssertionInfo const&) [node]
11: 0xf42264  [node]
12: 0x7f3d09e45495  [/lib/x86_64-linux-gnu/libc.so.6]
13: 0x7f3d09e45610 on_exit [/lib/x86_64-linux-gnu/libc.so.6]
14: 0xe98a4f node::DefaultProcessExitHandlerInternal(node::Environment*, node::ExitCode) [node]
15: 0xf01e4f node::Environment::Exit(node::ExitCode) [node]
16: 0x1d755e2  [node]
